### ISSUE TITLE
Crash on index page

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/capstone_monitor#7]
```
Traceback (most recent call last):
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/www/capstone_monitor.py", line 74, in index
    return render_template("index.html",node_data=node_data, isadmin=is_admin(person))
                                                                     ^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/www/capstone_monitor.py", line 208, in is_admin
    _,groups = groups.stdout.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by s-andrews** [comment]
Never could replicate this...
