### ISSUE TITLE
Crash on allstorage

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/capstone_monitor#8]
```
Traceback (most recent call last):
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bi/home/andrewss/capstone_monitor/www/capstone_monitor.py", line 182, in allstorage
    size += datapoint["data"][person["username"]][share]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/bi/group'
```

**Comment by s-andrews** [comment]
This makes no sense.  I'm literally iterating through the keys of a data structure, which it then says doesn't exist in that structure???
